package com.example.libreria_universitaria;

import com.example.libreria_universitaria.entity.Libro;
import com.example.libreria_universitaria.repository.LibroRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.HashSet;
import java.util.Set;

@SpringBootApplication
public class LibreriaUniversitariaApplication implements ApplicationRunner {

	@Autowired
	private LibroRepository libroRepository;

	public static void main(String[] args) {
		SpringApplication.run(LibreriaUniversitariaApplication.class, args);
	}

	@Override
	public void run(ApplicationArguments args) throws Exception {
		populateBiblioteca();
	}

	private void populateBiblioteca() {
		Set<Libro> listaLibri = new HashSet<>(Set.of(
				new Libro("Il Signore degli Anelli", "J.R.R. Tolkien", 1954, "Fantasy", true, 39.99),
				new Libro("1984", "George Orwell", 1949, "Distopico", true, 19.99),
				new Libro("Il Nome della Rosa", "Umberto Eco", 1980, "Storico", false, 25.50),
				new Libro("La coscienza di Zeno", "Italo Svevo", 1923, "Romanzo Psicologico", true, 18.75),
				new Libro("Harry Potter e la Pietra Filosofale", "J.K. Rowling", 1997, "Fantasy", true, 24.99),
				new Libro("Il Gattopardo", "Giuseppe Tomasi di Lampedusa", 1958, "Storico", true, 22.00),
				new Libro("Orgoglio e Pregiudizio", "Jane Austen", 1813, "Romanzo", false, 17.00),
				new Libro("Il Codice da Vinci", "Dan Brown", 2003, "Thriller", true, 21.90),
				new Libro("Siddhartha", "Hermann Hesse", 1922, "Spirituale", true, 16.50),
				new Libro("I Promessi Sposi", "Alessandro Manzoni", 1840, "Classico", true, 14.99),
				new Libro("Delitto e Castigo", "Fëdor Dostoevskij", 1866, "Classico", true, 18.99),
				new Libro("Il Processo", "Franz Kafka", 1925, "Esistenziale", true, 15.49),
				new Libro("Don Chisciotte della Mancia", "Miguel de Cervantes", 1605, "Romanzo Cavalleresco", true, 19.99),
				new Libro("Il Piccolo Principe", "Antoine de Saint-Exupéry", 1943, "Fiaba", true, 12.99),
				new Libro("Il Maestro e Margherita", "Michail Bulgakov", 1967, "Satirico", true, 17.50),
				new Libro("Cent'anni di solitudine", "Gabriel García Márquez", 1967, "Realismo Magico", true, 20.00),
				new Libro("Moby Dick", "Herman Melville", 1851, "Avventura", false, 18.00),
				new Libro("Il vecchio e il mare", "Ernest Hemingway", 1952, "Narrativa", true, 13.99),
				new Libro("Dracula", "Bram Stoker", 1897, "Horror", true, 16.80),
				new Libro("Frankenstein", "Mary Shelley", 1818, "Horror", true, 14.50),
				new Libro("Lo Hobbit", "J.R.R. Tolkien", 1937, "Fantasy", true, 21.99),
				new Libro("Le avventure di Sherlock Holmes", "Arthur Conan Doyle", 1892, "Giallo", true, 15.00),
				new Libro("Il ritratto di Dorian Gray", "Oscar Wilde", 1890, "Classico", true, 16.75),
				new Libro("Il barone rampante", "Italo Calvino", 1957, "Narrativa", false, 19.50),
				new Libro("Il deserto dei Tartari", "Dino Buzzati", 1940, "Esistenziale", true, 17.90),
				new Libro("Fahrenheit 451", "Ray Bradbury", 1953, "Distopico", true, 14.99),
				new Libro("Il giovane Holden", "J.D. Salinger", 1951, "Narrativa", false, 15.99),
				new Libro("La Metamorfosi", "Franz Kafka", 1915, "Surrealismo", true, 11.50),
				new Libro("Il Grande Gatsby", "F. Scott Fitzgerald", 1925, "Classico", true, 14.20),
				new Libro("Jane Eyre", "Charlotte Brontë", 1847, "Romanzo", true, 18.40),
				new Libro("Cime tempestose", "Emily Brontë", 1847, "Romanzo Gotico", true, 17.30),
				new Libro("Oliver Twist", "Charles Dickens", 1837, "Classico", false, 16.10),
				new Libro("David Copperfield", "Charles Dickens", 1850, "Classico", true, 19.00),
				new Libro("Anna Karenina", "Lev Tolstoj", 1877, "Romanzo", true, 21.50),
				new Libro("Guerra e pace", "Lev Tolstoj", 1869, "Storico", true, 24.00),
				new Libro("Zanna Bianca", "Jack London", 1906, "Avventura", true, 12.80),
				new Libro("Il richiamo della foresta", "Jack London", 1903, "Avventura", true, 13.60),
				new Libro("Cuore", "Edmondo De Amicis", 1886, "Narrativa per ragazzi", true, 11.90),
				new Libro("Il diario di Anna Frank", "Anne Frank", 1947, "Biografia", true, 15.99),
				new Libro("Se questo è un uomo", "Primo Levi", 1947, "Memoriale", true, 14.80),
				new Libro("La tregua", "Primo Levi", 1963, "Memoriale", true, 15.20),
				new Libro("Il mondo nuovo", "Aldous Huxley", 1932, "Distopico", true, 17.40),
				new Libro("Shining", "Stephen King", 1977, "Horror", false, 22.10),
				new Libro("It", "Stephen King", 1986, "Horror", true, 25.60),
				new Libro("Carrie", "Stephen King", 1974, "Horror", true, 18.30),
				new Libro("Misery", "Stephen King", 1987, "Thriller", true, 20.00),
				new Libro("Norwegian Wood", "Haruki Murakami", 1987, "Romanzo", true, 16.90),
				new Libro("Kafka sulla spiaggia", "Haruki Murakami", 2002, "Narrativa", true, 18.70),
				new Libro("1Q84", "Haruki Murakami", 2009, "Fantastico", true, 22.30),
				new Libro("La strada", "Cormac McCarthy", 2006, "Post-apocalittico", true, 17.50),
				new Libro("American Psycho", "Bret Easton Ellis", 1991, "Satira", false, 18.90),
				new Libro("Il cacciatore di aquiloni", "Khaled Hosseini", 2003, "Drammatico", true, 19.20),
				new Libro("Mille splendidi soli", "Khaled Hosseini", 2007, "Drammatico", true, 20.30),
				new Libro("L'amica geniale", "Elena Ferrante", 2011, "Narrativa", true, 16.99),
				new Libro("Storia del nuovo cognome", "Elena Ferrante", 2012, "Narrativa", true, 17.49),
				new Libro("L'isola di Arturo", "Elsa Morante", 1957, "Narrativa", true, 15.99),
				new Libro("Aracoeli", "Elsa Morante", 1982, "Narrativa", false, 13.99),
				new Libro("Lessico famigliare", "Natalia Ginzburg", 1963, "Memoriale", true, 14.20),
				new Libro("Quer pasticciaccio brutto de via Merulana", "Carlo Emilio Gadda", 1957, "Giallo", true, 18.60),
				new Libro("Cristo si è fermato a Eboli", "Carlo Levi", 1945, "Biografico", true, 16.40),
				new Libro("Il giorno della civetta", "Leonardo Sciascia", 1961, "Giallo", true, 15.50),
				new Libro("A ciascuno il suo", "Leonardo Sciascia", 1966, "Giallo", true, 15.90),
				new Libro("Il visconte dimezzato", "Italo Calvino", 1952, "Allegorico", true, 12.50),
				new Libro("Il cavaliere inesistente", "Italo Calvino", 1959, "Fiabesco", true, 13.00),
				new Libro("Marcovaldo", "Italo Calvino", 1963, "Narrativa", true, 14.30),
				new Libro("Cosmicomiche", "Italo Calvino", 1965, "Fantascienza", false, 13.50),
				new Libro("Il fu Mattia Pascal", "Luigi Pirandello", 1904, "Esistenziale", true, 12.99),
				new Libro("Uno, nessuno e centomila", "Luigi Pirandello", 1926, "Esistenziale", true, 13.20),
				new Libro("La patente", "Luigi Pirandello", 1917, "Umoristico", true, 10.99),
				new Libro("Ninfee nere", "Michel Bussi", 2011, "Thriller", true, 17.00),
				new Libro("L'uomo che scambiò sua moglie per un cappello", "Oliver Sacks", 1985, "Saggistica", true, 14.90),
				new Libro("Breve storia del tempo", "Stephen Hawking", 1988, "Divulgazione", true, 16.99),
				new Libro("Sapiens", "Yuval Noah Harari", 2011, "Saggistica", true, 22.00),
				new Libro("Homo Deus", "Yuval Noah Harari", 2015, "Saggistica", true, 23.00),
				new Libro("21 lezioni per il XXI secolo", "Yuval Noah Harari", 2018, "Saggistica", true, 24.00),
				new Libro("La ragazza del treno", "Paula Hawkins", 2015, "Thriller", true, 18.00),
				new Libro("La verità sul caso Harry Quebert", "Joël Dicker", 2012, "Thriller", true, 19.00),
				new Libro("L'uomo di gesso", "C.J. Tudor", 2018, "Thriller", true, 17.90),
				new Libro("La psichiatra", "Wulf Dorn", 2009, "Thriller", true, 18.30),
				new Libro("Il suggeritore", "Donato Carrisi", 2009, "Thriller", true, 17.60),
				new Libro("Il tribunale delle anime", "Donato Carrisi", 2011, "Thriller", true, 18.10),
				new Libro("La ragazza nella nebbia", "Donato Carrisi", 2015, "Thriller", true, 17.80),
				new Libro("Il gioco del suggeritore", "Donato Carrisi", 2018, "Thriller", true, 19.40),
				new Libro("Il labirinto degli spiriti", "Carlos Ruiz Zafón", 2016, "Narrativa", true, 20.00),
				new Libro("L'ombra del vento", "Carlos Ruiz Zafón", 2001, "Narrativa", true, 19.00),
				new Libro("Il prigioniero del cielo", "Carlos Ruiz Zafón", 2011, "Narrativa", true, 18.50),
				new Libro("Il gioco dell'angelo", "Carlos Ruiz Zafón", 2008, "Narrativa", true, 17.90),
				new Libro("Dance Dance Dance", "Haruki Murakami", 1988, "Surreale", true, 17.60),
				new Libro("Nel segno della pecora", "Haruki Murakami", 1982, "Surreale", true, 16.30),
				new Libro("La fine del mondo e il paese delle meraviglie", "Haruki Murakami", 1985, "Surreale", true, 18.10),
				new Libro("After Dark", "Haruki Murakami", 2004, "Narrativa", true, 14.70),
				new Libro("Colorless Tsukuru Tazaki", "Haruki Murakami", 2013, "Narrativa", true, 19.20),
				new Libro("Sputnik Sweetheart", "Haruki Murakami", 1999, "Narrativa", true, 15.80),
				new Libro("A sud del confine, a ovest del sole", "Haruki Murakami", 1992, "Narrativa", true, 15.60),
				new Libro("Underground", "Haruki Murakami", 1997, "Saggio", true, 18.90),
				new Libro("Il giovane Marx", "Eric Hobsbawm", 2010, "Biografia", true, 21.50),
				new Libro("Il buio oltre la siepe", "Harper Lee", 1960, "Narrativa", true, 18.00),
				new Libro("La collina dei conigli", "Richard Adams", 1972, "Fantasy", true, 17.20),
				new Libro("La strada", "Cormac McCarthy", 2006, "Post-apocalittico", true, 17.50),
				new Libro("American Psycho", "Bret Easton Ellis", 1991, "Satira", false, 18.90),
				new Libro("Il cacciatore di aquiloni", "Khaled Hosseini", 2003, "Drammatico", true, 19.20),
				new Libro("Mille splendidi soli", "Khaled Hosseini", 2007, "Drammatico", true, 20.30),
				new Libro("L'amica geniale", "Elena Ferrante", 2011, "Narrativa", true, 16.99),
				new Libro("Storia del nuovo cognome", "Elena Ferrante", 2012, "Narrativa", true, 17.49),
				new Libro("L'isola di Arturo", "Elsa Morante", 1957, "Narrativa", true, 15.99),
				new Libro("Aracoeli", "Elsa Morante", 1982, "Narrativa", false, 13.99),
				new Libro("Lessico famigliare", "Natalia Ginzburg", 1963, "Memoriale", true, 14.20),
				new Libro("Quer pasticciaccio...", "Carlo Emilio Gadda", 1957, "Giallo", true, 18.60),
				new Libro("Cristo si è fermato a Eboli", "Carlo Levi", 1945, "Biografico", true, 16.40),
				new Libro("Il giorno della civetta", "Leonardo Sciascia", 1961, "Giallo", true, 15.50),
				new Libro("A ciascuno il suo", "Leonardo Sciascia", 1966, "Giallo", true, 15.90),
				new Libro("Il visconte dimezzato", "Italo Calvino", 1952, "Allegorico", true, 12.50),
				new Libro("Il cavaliere inesistente", "Italo Calvino", 1959, "Fiabesco", true, 13.00),
				new Libro("Marcovaldo", "Italo Calvino", 1963, "Narrativa", true, 14.30),
				new Libro("Cosmicomiche", "Italo Calvino", 1965, "Fantascienza", false, 13.50),
				new Libro("Il fu Mattia Pascal", "Luigi Pirandello", 1904, "Esistenziale", true, 12.99),
				new Libro("Uno, nessuno e centomila", "Luigi Pirandello", 1926, "Esistenziale", true, 13.20),
				new Libro("La patente", "Luigi Pirandello", 1917, "Umoristico", true, 10.99),
				new Libro("Ninfee nere", "Michel Bussi", 2011, "Thriller", true, 17.00),
				new Libro("L’uomo che scambiò...", "Oliver Sacks", 1985, "Saggistica", true, 14.90),
				new Libro("Breve storia del tempo", "Stephen Hawking", 1988, "Divulgazione", true, 16.99),
				new Libro("Sapiens", "Yuval Noah Harari", 2011, "Saggistica", true, 22.00),
				new Libro("Homo Deus", "Yuval Noah Harari", 2015, "Saggistica", true, 23.00),
				new Libro("21 lezioni per il XXI secolo", "Yuval Noah Harari", 2018, "Saggistica", true, 24.00),
				new Libro("La ragazza del treno", "Paula Hawkins", 2015, "Thriller", true, 18.00),
				new Libro("La verità sul caso Harry Quebert", "Joël Dicker", 2012, "Thriller", true, 19.00),
				new Libro("L’uomo di gesso", "C.J. Tudor", 2018, "Thriller", true, 17.90),
				new Libro("La psichiatra", "Wulf Dorn", 2009, "Thriller", true, 18.30),
				new Libro("Il suggeritore", "Donato Carrisi", 2009, "Thriller", true, 17.60),
				new Libro("Il tribunale delle anime", "Donato Carrisi", 2011, "Thriller", true, 18.10),
				new Libro("La ragazza nella nebbia", "Donato Carrisi", 2015, "Thriller", true, 17.80),
				new Libro("Il gioco del suggeritore", "Donato Carrisi", 2018, "Thriller", true, 19.40),
				new Libro("Il labirinto degli spiriti", "Carlos Ruiz Zafón", 2016, "Narrativa", true, 20.00),
				new Libro("L’ombra del vento", "Carlos Ruiz Zafón", 2001, "Narrativa", true, 19.00),
				new Libro("Il prigioniero del cielo", "Carlos Ruiz Zafón", 2011, "Narrativa", true, 18.50),
				new Libro("Il gioco dell’angelo", "Carlos Ruiz Zafón", 2008, "Narrativa", true, 17.90),
				new Libro("Dance Dance Dance", "Haruki Murakami", 1988, "Surreale", true, 17.60),
				new Libro("Nel segno della pecora", "Haruki Murakami", 1982, "Surreale", true, 16.30),
				new Libro("La fine del mondo...", "Haruki Murakami", 1985, "Surreale", true, 18.10),
				new Libro("After Dark", "Haruki Murakami", 2004, "Narrativa", true, 14.70),
				new Libro("Colorless Tsukuru Tazaki", "Haruki Murakami", 2013, "Narrativa", true, 19.20),
				new Libro("Sputnik Sweetheart", "Haruki Murakami", 1999, "Narrativa", true, 15.80),
				new Libro("A sud del confine…", "Haruki Murakami", 1992, "Narrativa", true, 15.60),
				new Libro("Underground", "Haruki Murakami", 1997, "Saggio", true, 18.90),
				new Libro("La solitudine dei numeri primi", "Paolo Giordano", 2008, "Narrativa", true, 16.40),
				new Libro("La casa degli spiriti", "Isabel Allende", 1982, "Realismo Magico", true, 17.40),
				new Libro("La mia Africa", "Karen Blixen", 1937, "Memoriale", true, 16.00),
				new Libro("Memorie di Adriano", "Marguerite Yourcenar", 1951, "Storico", true, 18.70),
				new Libro("Il bar sotto il mare", "Simone Lenzi", 2019, "Narrativa", true, 14.60),
				new Libro("L'accabadora", "Sandro Veronesi", 2002, "Narrativa", true, 15.10)
		));

		libroRepository.saveAll(listaLibri);
	}
}
